# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8525d96d65b88a498896d1e1681ace804170dc99cea45f7b12ac9f2a0e388e5b772f5f5f4b9a73b1f831f19b41e01487c5c2de1e7633dadb506b77eecc367c

test:
  secret_key_base: d9b0e04ba6631dcf73e13477d1984a43293fc25c418e9919f4e052c425c5356786f6f2f75cd0fa777da34414ad52592535b64997214a12c8f20ec7dc803af506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
